// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeuepyucpafcjibsofec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpldWVweXVjcGFmY2ppYnNvZmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTAzOTUsImV4cCI6MjA1ODIyNjM5NX0.lTh2dMo_6yYYDfi6j_AvlACeJq4Z4HFiP5kK_ZHck0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);